version: 2

jobs:
    build:
        docker:
            -
                image: circleci/golang:1.11

        working_directory: /go/src/github.com/sagikazarmark/modern-go-application

        steps:
            - checkout

            -
                restore_cache:
                    name: Restore build dependencies
                    keys:
                        - build-deps-v1-{{ .Branch }}-{{ checksum "Makefile" }}

            -
                run:
                    name: Run tests
                    command: make test
                    environment:
                        VERBOSE: 1

            -
                run:
                    name: Run linter
                    command: make lint

            -
                save_cache:
                    name: Save build dependencies
                    key: build-deps-v1-{{ .Branch }}-{{ checksum "Makefile" }}
                    paths:
                        - bin/
